In [1]:
%cd /workspace/megatron/Megatron-LM-working

/workspace/megatron/Megatron-LM-working


In [2]:
!ls

LICENSE		   detokenizer.py	logsrs.txt	  pretrain_gpt2.py
README.md	   docker		model		  requirements.txt
__pycache__	   evaluate_gpt2.py	mpu		  scripts
arguments.py	   fp16			notebooks	  utils.py
cache		   generate_samples.py	nsight_op	  xlnet
configure_data.py  gpt2_data_loader.py	nsight_op.qdstrm
data		   learning_rates.py	openwebtext
data_utils	   log.txt		pretrain_bert.py


In [3]:
! /opt/nvidia/nsight-systems/2019.6.1/bin/nsys profile -w true -t "cudnn,cuda,osrt,nvtx,cublas" --cudabacktrace true --trace-fork-before-exec true -o /workspace/megatron/Megatron-LM-working/nsight_op/meow_gpu --force-overwrite true bash scripts/pretrain_gpt2_model_parallel.sh


**** collection configuration ****
	output_filename = /workspace/megatron/Megatron-LM-working/nsight_op/meow_gpu
	force-overwrite = true
	stop-on-exit = true
	export_sqlite = false
	stats = false
	capture-range = none
	stop-on-range-end = false
	delay = 0 seconds
	duration = 0 seconds
	kill = signal number 15
	inherit-environment = true
	show-output = true
	wait = all
	application command = bash
	application arguments = scripts/pretrain_gpt2_model_parallel.sh 
	application working directory = /workspace/megatron/Megatron-LM-working
	NVTX profiler range trigger = 
	NVTX profiler domain trigger = 
	environment variables:

	application configuration
	    sample_cpu = true
	    backtrace_method = lbr
	    trace_cublas = true
	    trace_cuda = true
	    trace_cudnn = true
	    trace_nvtx = true
	    trace_mpi = false
	    trace_openacc = false
	    trace_vulkan = false
	    trace_opengl = false
	    trace_osrt = true
	    osrt-threshold = 0 nanoseconds
	    cudabacktrace = true
	    cudaba

In [5]:
import mpu

In [ ]:
print(mpu._MODEL_PARALLEL_GROUP)

In [15]:
!bash scripts/pretrain_gpt2_model_parallel.sh

device= 5
local 5
using world size: 6 and model-parallel size: 2 
 > using dynamic loss scaling
device= 0
local 0
device= 4
local 4
4 range(4, 6)
barrier ahead
device= 2
local 2
2 range(2, 4)
barrier ahead
device= 3
local 3
3 range(2, 4)
barrier ahead
device= 1
local 1
1 range(0, 2)
barrier ahead
5 range(4, 6)
barrier ahead
> initializing model parallel with size 2
0 range(0, 2)
Pretrain GPT2 model
arguments:
  pretrained_bert .............. False
  attention_dropout ............ 0.1
  num_attention_heads .......... 16
  hidden_size .................. 1024
  intermediate_size ............ None
  num_layers ................... 24
  layernorm_epsilon ............ 1e-05
  hidden_dropout ............... 0.1
  max_position_embeddings ...... 1024
  vocab_size ................... 30522
  deep_init .................... False
  make_vocab_size_divisible_by . 128
  fp16 ......................... True
  fp32_embedding ............... False
  fp32_layernorm ............... False
  fp32_tokentypes 

input ids torch.Size([8, 1024]) cuda:1
input ids torch.Size([8, 1024]) cuda:0
input ids torch.Size([8, 1024]) cuda:5
input ids torch.Size([8, 1024]) cuda:4
input ids torch.Size([8, 1024]) cuda:3
input ids torch.Size([8, 1024]) cuda:2
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0022, -0.0099,  0.0033,  ..., -0.0329, -0.0202, -0.0071],
        [ 0.0108,  0.0178, -0.0054,  ..., -0.0207, -0.0296, -0.0145],
        [ 0.0294, -0.0160, -0.0213,  ...,  0.0323, -0.0444, -0.0457],
        ...,
        [ 0.0167, -0.0156, -0.0097,  ..., -0.0159,  0.0259, -0.0144],
        [-0.0125,  0.0065, -0.0119,  ..., -0.0235, -0.0248, -0.0275],
        [-0.0134, -0.0116,  0.0125,  ...,  0.0226,  0.0131, -0.0371]],
       device='cuda:0', dtype=torch.float16, requires_grad=True) cuda:0
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0183, -0.0328, -0.0041,  ...,  0.0030, -0.0033,  0.0005],
        [-0.0010,  0.0244, -0.0139,  ..., -0.0359, -0.0075,  0

input ids torch.Size([8, 1024]) cuda:1
input ids torch.Size([8, 1024]) cuda:5
input ids torch.Size([8, 1024]) cuda:3
input ids torch.Size([8, 1024]) cuda:4
input ids torch.Size([8, 1024]) cuda:0
input ids torch.Size([8, 1024]) cuda:2
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0183, -0.0328, -0.0041,  ...,  0.0030, -0.0033,  0.0005],
        [-0.0010,  0.0244, -0.0139,  ..., -0.0359, -0.0075,  0.0154],
        [ 0.0244,  0.0100, -0.0251,  ..., -0.0246, -0.0171, -0.0110],
        ...,
        [ 0.0189, -0.0137,  0.0094,  ...,  0.0226, -0.0199, -0.0213],
        [ 0.0221,  0.0361,  0.0029,  ..., -0.0299, -0.0145,  0.0146],
        [-0.0243, -0.0330, -0.0122,  ...,  0.0123,  0.0193,  0.0159]],
       device='cuda:5', dtype=torch.float16, requires_grad=True) cuda:5
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0183, -0.0328, -0.0041,  ...,  0.0030, -0.0033,  0.0005],
        [-0.0010,  0.0244, -0.0139,  ..., -0.0359, -0.0075,  0

word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0183, -0.0328, -0.0041,  ...,  0.0030, -0.0033,  0.0005],
        [-0.0010,  0.0244, -0.0139,  ..., -0.0359, -0.0075,  0.0154],
        [ 0.0244,  0.0100, -0.0251,  ..., -0.0246, -0.0171, -0.0110],
        ...,
        [ 0.0189, -0.0137,  0.0094,  ...,  0.0226, -0.0199, -0.0213],
        [ 0.0221,  0.0361,  0.0029,  ..., -0.0299, -0.0145,  0.0146],
        [-0.0243, -0.0330, -0.0122,  ...,  0.0123,  0.0193,  0.0159]],
       device='cuda:5', dtype=torch.float16, requires_grad=True)word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0022, -0.0099,  0.0033,  ..., -0.0329, -0.0202, -0.0071],
        [ 0.0108,  0.0178, -0.0054,  ..., -0.0207, -0.0296, -0.0145],
        [ 0.0294, -0.0160, -0.0213,  ...,  0.0323, -0.0444, -0.0457],
        ...,
        [ 0.0167, -0.0156, -0.0097,  ..., -0.0159,  0.0259, -0.0144],
        [-0.0125,  0.0065, -0.0119,  ..., -0.0235, -0.0248, -0.0275],
        [-0

input ids torch.Size([8, 1024]) cuda:3
input ids torch.Size([8, 1024]) cuda:1
input ids torch.Size([8, 1024]) cuda:5
input ids torch.Size([8, 1024]) cuda:0
input ids torch.Size([8, 1024]) cuda:2
input ids torch.Size([8, 1024]) cuda:4
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0022, -0.0099,  0.0033,  ..., -0.0329, -0.0202, -0.0071],
        [ 0.0108,  0.0178, -0.0054,  ..., -0.0207, -0.0296, -0.0145],
        [ 0.0294, -0.0160, -0.0213,  ...,  0.0323, -0.0444, -0.0457],
        ...,
        [ 0.0167, -0.0156, -0.0097,  ..., -0.0159,  0.0259, -0.0144],
        [-0.0125,  0.0065, -0.0119,  ..., -0.0235, -0.0248, -0.0275],
        [-0.0134, -0.0116,  0.0125,  ...,  0.0226,  0.0131, -0.0371]],
       device='cuda:2', dtype=torch.float16, requires_grad=True) cuda:2
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0183, -0.0328, -0.0041,  ...,  0.0030, -0.0033,  0.0005],
        [-0.0010,  0.0244, -0.0139,  ..., -0.0359, -0.0075,  0

input ids torch.Size([8, 1024]) cuda:5
input ids torch.Size([8, 1024]) cuda:3
input ids torch.Size([8, 1024]) cuda:1
input ids torch.Size([8, 1024]) cuda:0
input ids torch.Size([8, 1024]) cuda:4
input ids torch.Size([8, 1024]) cuda:2
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0022, -0.0099,  0.0033,  ..., -0.0329, -0.0202, -0.0071],
        [ 0.0108,  0.0178, -0.0054,  ..., -0.0207, -0.0296, -0.0145],
        [ 0.0294, -0.0160, -0.0213,  ...,  0.0323, -0.0444, -0.0457],
        ...,
        [ 0.0167, -0.0156, -0.0097,  ..., -0.0159,  0.0259, -0.0144],
        [-0.0125,  0.0065, -0.0119,  ..., -0.0235, -0.0248, -0.0275],
        [-0.0134, -0.0116,  0.0125,  ...,  0.0226,  0.0131, -0.0371]],
       device='cuda:2', dtype=torch.float16, requires_grad=True)word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0183, -0.0328, -0.0041,  ...,  0.0030, -0.0033,  0.0005],
        [-0.0010,  0.0244, -0.0139,  ..., -0.0359, -0.0075,  0.0154],


input ids torch.Size([8, 1024]) cuda:3
input ids torch.Size([8, 1024]) cuda:1
input ids torch.Size([8, 1024]) cuda:5
input ids torch.Size([8, 1024]) cuda:0
input ids torch.Size([8, 1024]) cuda:2
input ids torch.Size([8, 1024]) cuda:4
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0022, -0.0099,  0.0033,  ..., -0.0329, -0.0202, -0.0071],
        [ 0.0108,  0.0178, -0.0054,  ..., -0.0207, -0.0296, -0.0145],
        [ 0.0294, -0.0160, -0.0213,  ...,  0.0323, -0.0444, -0.0457],
        ...,
        [ 0.0167, -0.0156, -0.0097,  ..., -0.0159,  0.0259, -0.0144],
        [-0.0125,  0.0065, -0.0119,  ..., -0.0235, -0.0248, -0.0275],
        [-0.0134, -0.0116,  0.0125,  ...,  0.0226,  0.0131, -0.0371]],
       device='cuda:2', dtype=torch.float16, requires_grad=True)word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0183, -0.0328, -0.0041,  ...,  0.0030, -0.0033,  0.0005],
        [-0.0010,  0.0244, -0.0139,  ..., -0.0359, -0.0075,  0.0154],


input ids torch.Size([8, 1024]) cuda:1
input ids torch.Size([8, 1024]) cuda:5
input ids torch.Size([8, 1024]) cuda:0
input ids torch.Size([8, 1024]) cuda:4
input ids torch.Size([8, 1024]) cuda:3
input ids torch.Size([8, 1024]) cuda:2
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0183, -0.0328, -0.0041,  ...,  0.0030, -0.0033,  0.0005],
        [-0.0010,  0.0244, -0.0139,  ..., -0.0359, -0.0075,  0.0154],
        [ 0.0244,  0.0100, -0.0251,  ..., -0.0246, -0.0171, -0.0110],
        ...,
        [ 0.0189, -0.0137,  0.0094,  ...,  0.0226, -0.0199, -0.0213],
        [ 0.0221,  0.0361,  0.0029,  ..., -0.0299, -0.0145,  0.0146],
        [-0.0243, -0.0330, -0.0122,  ...,  0.0123,  0.0193,  0.0159]],
       device='cuda:5', dtype=torch.float16, requires_grad=True) cuda:5
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0022, -0.0099,  0.0033,  ..., -0.0329, -0.0202, -0.0071],
        [ 0.0108,  0.0178, -0.0054,  ..., -0.0207, -0.0296, -0

input ids torch.Size([8, 1024]) cuda:3
input ids torch.Size([8, 1024]) cuda:1
input ids torch.Size([8, 1024]) cuda:5
input ids torch.Size([8, 1024]) cuda:0
input ids torch.Size([8, 1024]) cuda:2
input ids torch.Size([8, 1024]) cuda:4
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0022, -0.0099,  0.0033,  ..., -0.0329, -0.0202, -0.0071],
        [ 0.0108,  0.0178, -0.0054,  ..., -0.0207, -0.0296, -0.0145],
        [ 0.0294, -0.0160, -0.0213,  ...,  0.0323, -0.0444, -0.0457],
        ...,
        [ 0.0167, -0.0156, -0.0097,  ..., -0.0159,  0.0259, -0.0144],
        [-0.0125,  0.0065, -0.0119,  ..., -0.0235, -0.0248, -0.0275],
        [-0.0134, -0.0116,  0.0125,  ...,  0.0226,  0.0131, -0.0371]],
       device='cuda:2', dtype=torch.float16, requires_grad=True)word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0183, -0.0328, -0.0041,  ...,  0.0030, -0.0033,  0.0005],
        [-0.0010,  0.0244, -0.0139,  ..., -0.0359, -0.0075,  0.0154],


       device='cuda:3', dtype=torch.float16, requires_grad=True) cuda:3
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0183, -0.0328, -0.0041,  ...,  0.0030, -0.0033,  0.0005],
        [-0.0010,  0.0244, -0.0139,  ..., -0.0359, -0.0075,  0.0154],
        [ 0.0244,  0.0100, -0.0251,  ..., -0.0246, -0.0171, -0.0110],
        ...,
        [ 0.0189, -0.0137,  0.0094,  ...,  0.0226, -0.0199, -0.0213],
        [ 0.0221,  0.0361,  0.0029,  ..., -0.0299, -0.0145,  0.0146],
        [-0.0243, -0.0330, -0.0122,  ...,  0.0123,  0.0193,  0.0159]],
       device='cuda:5', dtype=torch.float16, requires_grad=True) cuda:5
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0022, -0.0099,  0.0033,  ..., -0.0329, -0.0202, -0.0071],
        [ 0.0108,  0.0178, -0.0054,  ..., -0.0207, -0.0296, -0.0145],
        [ 0.0294, -0.0160, -0.0213,  ...,  0.0323, -0.0444, -0.0457],
        ...,
        [ 0.0167, -0.0156, -0.0097,  ..., -0.0159,  0.0259, -0.0144],
 

input ids torch.Size([8, 1024]) cuda:1
input ids torch.Size([8, 1024]) cuda:5
input ids torch.Size([8, 1024]) cuda:3
input ids torch.Size([8, 1024]) cuda:0
input ids torch.Size([8, 1024]) cuda:4
input ids torch.Size([8, 1024]) cuda:2
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0022, -0.0099,  0.0033,  ..., -0.0329, -0.0202, -0.0071],
        [ 0.0108,  0.0178, -0.0054,  ..., -0.0207, -0.0296, -0.0145],
        [ 0.0294, -0.0160, -0.0213,  ...,  0.0323, -0.0444, -0.0457],
        ...,
        [ 0.0167, -0.0156, -0.0097,  ..., -0.0159,  0.0259, -0.0144],
        [-0.0125,  0.0065, -0.0119,  ..., -0.0235, -0.0248, -0.0275],
        [-0.0134, -0.0116,  0.0125,  ...,  0.0226,  0.0131, -0.0371]],
       device='cuda:2', dtype=torch.float16, requires_grad=True) cuda:2
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0183, -0.0328, -0.0041,  ...,  0.0030, -0.0033,  0.0005],
        [-0.0010,  0.0244, -0.0139,  ..., -0.0359, -0.0075,  0

input ids torch.Size([8, 1024]) cuda:1
input ids torch.Size([8, 1024]) cuda:5
input ids torch.Size([8, 1024]) cuda:3
input ids torch.Size([8, 1024]) cuda:0
input ids torch.Size([8, 1024]) cuda:2
input ids torch.Size([8, 1024]) cuda:4
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0022, -0.0099,  0.0033,  ..., -0.0329, -0.0202, -0.0071],
        [ 0.0108,  0.0178, -0.0054,  ..., -0.0207, -0.0296, -0.0145],
        [ 0.0294, -0.0160, -0.0213,  ...,  0.0323, -0.0444, -0.0457],
        ...,
        [ 0.0167, -0.0156, -0.0097,  ..., -0.0159,  0.0259, -0.0144],
        [-0.0125,  0.0065, -0.0119,  ..., -0.0235, -0.0248, -0.0275],
        [-0.0134, -0.0116,  0.0125,  ...,  0.0226,  0.0131, -0.0371]],
       device='cuda:2', dtype=torch.float16, requires_grad=True)word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0183, -0.0328, -0.0041,  ...,  0.0030, -0.0033,  0.0005],
        [-0.0010,  0.0244, -0.0139,  ..., -0.0359, -0.0075,  0.0154],


input ids torch.Size([8, 1024]) cuda:3
input ids torch.Size([8, 1024]) cuda:1
input ids torch.Size([8, 1024]) cuda:5
input ids torch.Size([8, 1024]) cuda:0
input ids torch.Size([8, 1024]) cuda:4
input ids torch.Size([8, 1024]) cuda:2
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0022, -0.0099,  0.0033,  ..., -0.0329, -0.0202, -0.0071],
        [ 0.0108,  0.0178, -0.0054,  ..., -0.0207, -0.0296, -0.0145],
        [ 0.0294, -0.0160, -0.0213,  ...,  0.0323, -0.0444, -0.0457],
        ...,
        [ 0.0167, -0.0156, -0.0097,  ..., -0.0159,  0.0259, -0.0144],
        [-0.0125,  0.0065, -0.0119,  ..., -0.0235, -0.0248, -0.0275],
        [-0.0134, -0.0116,  0.0125,  ...,  0.0226,  0.0131, -0.0371]],
       device='cuda:2', dtype=torch.float16, requires_grad=True)word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0183, -0.0328, -0.0041,  ...,  0.0030, -0.0033,  0.0005],
        [-0.0010,  0.0244, -0.0139,  ..., -0.0359, -0.0075,  0.0154],


input ids torch.Size([8, 1024]) cuda:1
input ids torch.Size([8, 1024]) cuda:3
input ids torch.Size([8, 1024]) cuda:5
input ids torch.Size([8, 1024]) cuda:0
input ids torch.Size([8, 1024]) cuda:2
input ids torch.Size([8, 1024]) cuda:4
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0022, -0.0099,  0.0033,  ..., -0.0329, -0.0202, -0.0071],
        [ 0.0108,  0.0178, -0.0054,  ..., -0.0207, -0.0296, -0.0145],
        [ 0.0294, -0.0160, -0.0213,  ...,  0.0323, -0.0444, -0.0457],
        ...,
        [ 0.0167, -0.0156, -0.0097,  ..., -0.0159,  0.0259, -0.0144],
        [-0.0125,  0.0065, -0.0119,  ..., -0.0235, -0.0248, -0.0275],
        [-0.0134, -0.0116,  0.0125,  ...,  0.0226,  0.0131, -0.0371]],
       device='cuda:2', dtype=torch.float16, requires_grad=True) cuda:2
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0183, -0.0328, -0.0041,  ...,  0.0030, -0.0033,  0.0005],
        [-0.0010,  0.0244, -0.0139,  ..., -0.0359, -0.0075,  0

input ids torch.Size([8, 1024]) cuda:1
input ids torch.Size([8, 1024]) cuda:3
input ids torch.Size([8, 1024]) cuda:5
input ids torch.Size([8, 1024]) cuda:0
input ids torch.Size([8, 1024]) cuda:2
input ids torch.Size([8, 1024]) cuda:4
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0022, -0.0099,  0.0033,  ..., -0.0329, -0.0202, -0.0071],
        [ 0.0108,  0.0178, -0.0054,  ..., -0.0207, -0.0296, -0.0145],
        [ 0.0294, -0.0160, -0.0213,  ...,  0.0323, -0.0444, -0.0457],
        ...,
        [ 0.0167, -0.0156, -0.0097,  ..., -0.0159,  0.0259, -0.0144],
        [-0.0125,  0.0065, -0.0119,  ..., -0.0235, -0.0248, -0.0275],
        [-0.0134, -0.0116,  0.0125,  ...,  0.0226,  0.0131, -0.0371]],
       device='cuda:2', dtype=torch.float16, requires_grad=True) cuda:2
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0183, -0.0328, -0.0041,  ...,  0.0030, -0.0033,  0.0005],
        [-0.0010,  0.0244, -0.0139,  ..., -0.0359, -0.0075,  0

input ids torch.Size([8, 1024]) cuda:1
input ids torch.Size([8, 1024]) cuda:5
input ids torch.Size([8, 1024]) cuda:3
input ids torch.Size([8, 1024]) cuda:0
input ids torch.Size([8, 1024]) cuda:4
input ids torch.Size([8, 1024]) cuda:2
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0022, -0.0099,  0.0033,  ..., -0.0329, -0.0202, -0.0071],
        [ 0.0108,  0.0178, -0.0054,  ..., -0.0207, -0.0296, -0.0145],
        [ 0.0294, -0.0160, -0.0213,  ...,  0.0323, -0.0444, -0.0457],
        ...,
        [ 0.0167, -0.0156, -0.0097,  ..., -0.0159,  0.0259, -0.0144],
        [-0.0125,  0.0065, -0.0119,  ..., -0.0235, -0.0248, -0.0275],
        [-0.0134, -0.0116,  0.0125,  ...,  0.0226,  0.0131, -0.0371]],
       device='cuda:2', dtype=torch.float16, requires_grad=True) cuda:2
word_embeddings torch.Size([25216, 1024]) Parameter containing:
tensor([[-0.0183, -0.0328, -0.0041,  ...,  0.0030, -0.0033,  0.0005],
        [-0.0010,  0.0244, -0.0139,  ..., -0.0359, -0.0075,  0